import type { TeamMember, PromptTemplate, TrainingModule, AdoptionMetrics, UsageLog } from "./types";

export const demoTeamMembers: TeamMember[] = [
  {
    id: "mem_001",
    fullName: "Sarah Chen",
    email: "sarah.chen@acmecorp.example.test",
    role: "marketing",
    department: "Marketing",
    avatarInitials: "SC",
    promptsUsed: 342,
    adoptionScore: 94,
    trainingCompleted: 5,
    totalModules: 5,
    joinedAt: "2025-03-15T09:00:00Z",
  },
  {
    id: "mem_002",
    fullName: "Marcus Webb",
    email: "marcus.webb@acmecorp.example.test",
    role: "sales",
    department: "Sales",
    avatarInitials: "MW",
    promptsUsed: 287,
    adoptionScore: 88,
    trainingCompleted: 4,
    totalModules: 5,
    joinedAt: "2025-04-01T09:00:00Z",
  },
  {
    id: "mem_003",
    fullName: "Priya Nair",
    email: "priya.nair@acmecorp.example.test",
    role: "engineering",
    department: "Engineering",
    avatarInitials: "PN",
    promptsUsed: 215,
    adoptionScore: 76,
    trainingCompleted: 3,
    totalModules: 5,
    joinedAt: "2025-05-12T09:00:00Z",
  },
  {
    id: "mem_004",
    fullName: "James Okonkwo",
    email: "james.okonkwo@acmecorp.example.test",
    role: "support",
    department: "Customer Support",
    avatarInitials: "JO",
    promptsUsed: 198,
    adoptionScore: 71,
    trainingCompleted: 2,
    totalModules: 5,
    joinedAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "mem_005",
    fullName: "Elena Torres",
    email: "elena.torres@acmecorp.example.test",
    role: "hr",
    department: "People Operations",
    avatarInitials: "ET",
    promptsUsed: 156,
    adoptionScore: 82,
    trainingCompleted: 5,
    totalModules: 5,
    joinedAt: "2025-02-01T09:00:00Z",
  },
  {
    id: "mem_006",
    fullName: "David Park",
    email: "david.park@acmecorp.example.test",
    role: "executive",
    department: "Executive",
    avatarInitials: "DP",
    promptsUsed: 94,
    adoptionScore: 45,
    trainingCompleted: 1,
    totalModules: 5,
    joinedAt: "2025-01-10T09:00:00Z",
  },
];

export const demoPromptTemplates: PromptTemplate[] = [
  {
    id: "pt_001",
    title: "Cold Email Outreach",
    description: "Generate personalized cold outreach emails with company research woven in",
    category: "sales",
    promptText: "Write a concise cold email to [PROSPECT] at [COMPANY]. Reference their recent [EVENT/NEWS]. Keep it under 120 words. Include one clear CTA for a 15-minute call.",
    usageCount: 187,
    averageRating: 4.7,
    createdBy: "mem_002",
    createdAt: "2026-03-01T10:00:00Z",
    tags: ["email", "outreach", "personalization"],
  },
  {
    id: "pt_002",
    title: "Blog Post Outline",
    description: "SEO-optimized blog outline with target keywords and section structure",
    category: "marketing",
    promptText: "Create a blog post outline about [TOPIC]. Target keyword: [KEYWORD]. Include: H1 title, 5-7 H2 sections, meta description, and 3 related internal linking opportunities.",
    usageCount: 234,
    averageRating: 4.5,
    createdBy: "mem_001",
    createdAt: "2026-03-05T14:00:00Z",
    tags: ["content", "seo", "writing"],
  },
  {
    id: "pt_003",
    title: "Customer Support Response",
    description: "Empathetic support responses that resolve issues and reduce churn",
    category: "support",
    promptText: "You are a helpful support agent. The customer says: [CUSTOMER_MESSAGE]. Write a response that: 1) acknowledges their frustration, 2) provides a clear solution, 3) offers a next step. Keep it under 200 words.",
    usageCount: 312,
    averageRating: 4.8,
    createdBy: "mem_004",
    createdAt: "2026-03-10T08:00:00Z",
    tags: ["support", "templates", "canned-responses"],
  },
  {
    id: "pt_004",
    title: "Code Review Checklist",
    description: "Generate a structured code review covering bugs, style, performance, and security",
    category: "engineering",
    promptText: "Review this code for: 1) potential bugs, 2) style/readability issues, 3) performance optimizations, 4) security concerns. Code to review:\n```\n[CODE]\n```",
    usageCount: 156,
    averageRating: 4.3,
    createdBy: "mem_003",
    createdAt: "2026-03-15T11:00:00Z",
    tags: ["code", "review", "quality"],
  },
  {
    id: "pt_005",
    title: "Meeting Notes Summarizer",
    description: "Turn raw meeting transcripts into clean, action-oriented summaries",
    category: "productivity",
    promptText: "Summarize these meeting notes:\n\n[TRANSCRIPT]\n\nFormat: 1) Key decisions, 2) Action items with owners, 3) Open questions, 4) Next meeting date if mentioned.",
    usageCount: 278,
    averageRating: 4.6,
    createdBy: "mem_005",
    createdAt: "2026-03-20T09:00:00Z",
    tags: ["meetings", "notes", "productivity"],
  },
  {
    id: "pt_006",
    title: "Job Description Writer",
    description: "Generate inclusive, compelling job descriptions for any role",
    category: "hr",
    promptText: "Write a job description for [ROLE] at [COMPANY]. Include: about us, role overview, key responsibilities (5-7), required qualifications, nice-to-haves, benefits, and EEO statement.",
    usageCount: 94,
    averageRating: 4.4,
    createdBy: "mem_005",
    createdAt: "2026-04-01T08:00:00Z",
    tags: ["hiring", "templates", "writing"],
  },
  {
    id: "pt_007",
    title: "Sales Call Prep Sheet",
    description: "Research-backed prep sheet before any sales call",
    category: "sales",
    promptText: "Create a call prep sheet for [CONTACT] at [COMPANY]. Include: recent company news, LinkedIn summary, potential pain points, 3 discovery questions, and 2 value props tailored to their industry.",
    usageCount: 143,
    averageRating: 4.2,
    createdBy: "mem_002",
    createdAt: "2026-04-10T10:00:00Z",
    tags: ["sales", "research", "preparation"],
  },
  {
    id: "pt_008",
    title: "Data Insights Reporter",
    description: "Turn raw data tables into executive-ready narrative insights",
    category: "data_analysis",
    promptText: "Analyze this data:\n\n[DATA]\n\nProvide: 1) Top 3 insights, 2) Trends over time, 3) Anomalies or outliers, 4) One recommended action. Write for an executive audience.",
    usageCount: 112,
    averageRating: 4.1,
    createdBy: "mem_001",
    createdAt: "2026-04-20T13:00:00Z",
    tags: ["analytics", "reporting", "executive"],
  },
];

export const demoTrainingModules: TrainingModule[] = [
  {
    id: "tm_001",
    title: "ChatGPT Fundamentals",
    description: "Learn prompt basics, context windows, and how to get consistent results from ChatGPT",
    category: "productivity",
    durationMinutes: 45,
    difficulty: "beginner",
    completionRate: 92,
    enrolledCount: 6,
    completedCount: 5,
    lessons: 8,
    practiceScenario: "Rewrite a messy internal status update into a scoped AI request with audience, constraints, and acceptance criteria.",
    capabilityOutcome: "Learner can turn a real workflow need into a reusable prompt without leaking confidential context.",
  },
  {
    id: "tm_002",
    title: "Advanced Prompt Engineering",
    description: "Chain-of-thought, few-shot, role-based, and structured output techniques for power users",
    category: "productivity",
    durationMinutes: 90,
    difficulty: "advanced",
    completionRate: 58,
    enrolledCount: 6,
    completedCount: 3,
    lessons: 12,
    practiceScenario: "Build and compare three prompt variants for the same operations report, then explain which output should be trusted.",
    capabilityOutcome: "Learner can evaluate accuracy, assumptions, and decision-readiness instead of only producing more content.",
  },
  {
    id: "tm_003",
    title: "Claude for Technical Teams",
    description: "Code generation, debugging, system design reviews, and long-context document analysis with Claude",
    category: "engineering",
    durationMinutes: 75,
    difficulty: "intermediate",
    completionRate: 64,
    enrolledCount: 5,
    completedCount: 3,
    lessons: 10,
    practiceScenario: "Review a simulated architecture brief with Claude and capture risks, source anchors, and follow-up questions for the team.",
    capabilityOutcome: "Learner can use long-context review for engineering judgment while preserving human approval gates.",
  },
  {
    id: "tm_004",
    title: "AI for Sales & Marketing",
    description: "Prospecting, email sequences, competitive research, content calendars, and social copy with LLMs",
    category: "sales",
    durationMinutes: 60,
    difficulty: "intermediate",
    completionRate: 78,
    enrolledCount: 4,
    completedCount: 3,
    lessons: 9,
    practiceScenario: "Draft a prospecting sequence from approved messaging and mark any claims that require human verification before sending.",
    capabilityOutcome: "Learner can apply AI to role-specific outreach while keeping brand, compliance, and factual-review checks visible.",
  },
  {
    id: "tm_005",
    title: "Responsible AI & Data Safety",
    description: "Data handling policies, PII protection, bias awareness, and when not to use AI",
    category: "productivity",
    durationMinutes: 40,
    difficulty: "beginner",
    completionRate: 85,
    enrolledCount: 6,
    completedCount: 5,
    lessons: 6,
    practiceScenario: "Classify sample prompts as safe, needs-redaction, or blocked, then document the safer rewrite.",
    capabilityOutcome: "Learner can spot PII, proprietary data, bias risk, and cases where AI should not be used.",
  },
];

export const demoUsageLogs: UsageLog[] = [
  { id: "ul_001", memberId: "mem_001", promptTemplateId: "pt_002", channel: "chatgpt", timestamp: "2026-06-09T08:30:00Z", promptSummary: "Blog outline for 'AI adoption trends Q3 2026'", tokensUsed: 1240, feedback: "positive" },
  { id: "ul_002", memberId: "mem_002", promptTemplateId: "pt_001", channel: "claude", timestamp: "2026-06-09T09:15:00Z", promptSummary: "Cold email to Acme Corp CTO about partnership", tokensUsed: 890, feedback: "positive" },
  { id: "ul_003", memberId: "mem_004", promptTemplateId: "pt_003", channel: "chatgpt", timestamp: "2026-06-09T10:00:00Z", promptSummary: "Support response for billing dispute #4472", tokensUsed: 560, feedback: "neutral" },
  { id: "ul_004", memberId: "mem_003", promptTemplateId: "pt_004", channel: "copilot", timestamp: "2026-06-09T10:45:00Z", promptSummary: "Code review for auth middleware PR #238", tokensUsed: 2100, feedback: "positive" },
  { id: "ul_005", memberId: "mem_001", promptTemplateId: "pt_008", channel: "chatgpt", timestamp: "2026-06-09T11:30:00Z", promptSummary: "Q2 marketing campaign performance analysis", tokensUsed: 3400, feedback: "positive" },
  { id: "ul_006", memberId: "mem_005", promptTemplateId: "pt_006", channel: "claude", timestamp: "2026-06-09T12:00:00Z", promptSummary: "JD for Senior Product Designer role", tokensUsed: 780, feedback: "positive" },
  { id: "ul_007", memberId: "mem_002", promptTemplateId: "pt_007", channel: "chatgpt", timestamp: "2026-06-09T13:15:00Z", promptSummary: "Prep for Enterprise Solutions call at 2pm", tokensUsed: 1650, feedback: "positive" },
  { id: "ul_008", memberId: "mem_006", promptTemplateId: null, channel: "chatgpt", timestamp: "2026-06-09T07:45:00Z", promptSummary: "Summarize quarterly board report", tokensUsed: 890, feedback: "neutral" },
  { id: "ul_009", memberId: "mem_004", promptTemplateId: "pt_003", channel: "chatgpt", timestamp: "2026-06-08T16:20:00Z", promptSummary: "Respond to feature request from enterprise client", tokensUsed: 620, feedback: "positive" },
  { id: "ul_010", memberId: "mem_003", promptTemplateId: "pt_004", channel: "copilot", timestamp: "2026-06-08T15:00:00Z", promptSummary: "Review database migration scripts", tokensUsed: 2800, feedback: "positive" },
  { id: "ul_011", memberId: "mem_001", promptTemplateId: "pt_005", channel: "chatgpt", timestamp: "2026-06-08T13:00:00Z", promptSummary: "Summarize weekly marketing standup", tokensUsed: 450, feedback: "positive" },
  { id: "ul_012", memberId: "mem_002", promptTemplateId: null, channel: "chatgpt", timestamp: "2026-06-08T11:30:00Z", promptSummary: "Draft proposal response for RFP questions", tokensUsed: 3200, feedback: "negative" },
];

export const demoAdoptionMetrics: AdoptionMetrics = {
  totalTeamMembers: 6,
  activeUsers: 5,
  totalPromptsUsed: 1292,
  averageAdoptionScore: 76,
  overallTrainingCompletion: 67,
  promptsThisWeek: 87,
  promptsThisMonth: 342,
  trendingUp: true,
  topCategory: "productivity",
  totalPromptTemplates: 8,
  averageRating: 4.5,
};
