import type { CapabilityCheck, TeamMember, PromptTemplate, TrainingModule, AdoptionMetrics, UsageLog, PrePostTrainingBenchmark, ShadowAiToolSignal } from "./types";

export const demoTeamMembers: TeamMember[] = [
  {
    id: "mem_001",
    fullName: "Sarah Chen",
    email: "sarah.chen@acmecorp.example.test",
    role: "marketing",
    roleBenchmark: 85,
    department: "Marketing",
    avatarInitials: "SC",
    promptsUsed: 342,
    adoptionScore: 94,
    trainingCompleted: 5,
    totalModules: 5,
    adoptionCoachMemberId: null,
    nextCoachingAt: null,
    coachingFocus: null,
    managerSupportOwner: null,
    managerCheckInAt: null,
    managerSupportAction: null,
    workflowTransferReviewer: null,
    workflowTransferReviewAt: null,
    workflowTransferSuccessCriteria: null,
    joinedAt: "2025-03-15T09:00:00Z",
  },
  {
    id: "mem_002",
    fullName: "Marcus Webb",
    email: "marcus.webb@acmecorp.example.test",
    role: "sales",
    roleBenchmark: 82,
    department: "Sales",
    avatarInitials: "MW",
    promptsUsed: 287,
    adoptionScore: 88,
    trainingCompleted: 4,
    totalModules: 5,
    adoptionCoachMemberId: null,
    nextCoachingAt: null,
    coachingFocus: null,
    managerSupportOwner: null,
    managerCheckInAt: null,
    managerSupportAction: null,
    workflowTransferReviewer: null,
    workflowTransferReviewAt: null,
    workflowTransferSuccessCriteria: null,
    joinedAt: "2025-04-01T09:00:00Z",
  },
  {
    id: "mem_003",
    fullName: "Priya Nair",
    email: "priya.nair@acmecorp.example.test",
    role: "engineering",
    roleBenchmark: 80,
    department: "Engineering",
    avatarInitials: "PN",
    promptsUsed: 215,
    adoptionScore: 76,
    trainingCompleted: 3,
    totalModules: 5,
    adoptionCoachMemberId: "mem_001",
    nextCoachingAt: "2026-07-22T14:00:00Z",
    coachingFocus: "Pair on a live architecture-review workflow and practice challenging unsupported AI findings before approval.",
    managerSupportOwner: "Nora Patel · VP Engineering",
    managerCheckInAt: "2026-07-29T14:00:00Z",
    managerSupportAction: "Protect a weekly architecture-review practice block and remove one low-priority ticket so Priya can apply the workflow with source evidence.",
    workflowTransferReviewer: "Owen Hart · Engineering Enablement Lead",
    workflowTransferReviewAt: "2026-08-05T14:00:00Z",
    workflowTransferSuccessCriteria: "Validate that Priya independently completes one architecture-review workflow with source anchors, documented challenges to unsupported findings, and the required human approval handoff.",
    joinedAt: "2025-05-12T09:00:00Z",
  },
  {
    id: "mem_004",
    fullName: "James Okonkwo",
    email: "james.okonkwo@acmecorp.example.test",
    role: "support",
    roleBenchmark: 78,
    department: "Customer Support",
    avatarInitials: "JO",
    promptsUsed: 198,
    adoptionScore: 71,
    trainingCompleted: 2,
    totalModules: 5,
    adoptionCoachMemberId: "mem_005",
    nextCoachingAt: "2026-07-20T15:30:00Z",
    coachingFocus: "Review unsupported-claim detection in customer responses, then repeat the workflow with source annotations.",
    managerSupportOwner: "Amina Brooks · Support Director",
    managerCheckInAt: "2026-07-27T15:30:00Z",
    managerSupportAction: "Reserve two ticket-review practice sessions and give James an approved sandbox queue for source-checking responses before live use.",
    workflowTransferReviewer: "Maya Singh · Support Quality Lead",
    workflowTransferReviewAt: "2026-08-03T15:30:00Z",
    workflowTransferSuccessCriteria: "Observe James complete three live ticket-response workflows with source annotations and no unsupported claims, then record the quality review outcome.",
    joinedAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "mem_005",
    fullName: "Elena Torres",
    email: "elena.torres@acmecorp.example.test",
    role: "hr",
    roleBenchmark: 80,
    department: "People Operations",
    avatarInitials: "ET",
    promptsUsed: 156,
    adoptionScore: 82,
    trainingCompleted: 5,
    totalModules: 5,
    adoptionCoachMemberId: null,
    nextCoachingAt: null,
    coachingFocus: null,
    managerSupportOwner: null,
    managerCheckInAt: null,
    managerSupportAction: null,
    workflowTransferReviewer: null,
    workflowTransferReviewAt: null,
    workflowTransferSuccessCriteria: null,
    joinedAt: "2025-02-01T09:00:00Z",
  },
  {
    id: "mem_006",
    fullName: "David Park",
    email: "david.park@acmecorp.example.test",
    role: "executive",
    roleBenchmark: 75,
    department: "Executive",
    avatarInitials: "DP",
    promptsUsed: 94,
    adoptionScore: 45,
    trainingCompleted: 1,
    totalModules: 5,
    adoptionCoachMemberId: "mem_005",
    nextCoachingAt: "2026-07-18T16:00:00Z",
    coachingFocus: "Practice redacting board materials before model use and complete a safe executive-summary walkthrough.",
    managerSupportOwner: "Leah Monroe · Chief Operating Officer",
    managerCheckInAt: "2026-07-24T16:00:00Z",
    managerSupportAction: "Move the board-summary workflow into the approved workspace and review David's redaction checklist before the next executive briefing.",
    workflowTransferReviewer: "Elena Torres · People Operations",
    workflowTransferReviewAt: "2026-07-31T16:00:00Z",
    workflowTransferSuccessCriteria: "Confirm David prepares one board-summary workflow inside the approved workspace, applies the redaction checklist, and passes the human safety review before briefing use.",
    joinedAt: "2025-01-10T09:00:00Z",
  },
];

export const demoPromptTemplates: PromptTemplate[] = [
  {
    id: "pt_001",
    title: "Cold Email Outreach",
    description: "Generate personalized cold outreach emails with company research woven in",
    category: "sales",
    promptText: "Write a concise cold email to [PROSPECT] at [COMPANY]. Reference their recent [EVENT/NEWS]. Keep it under 120 words. Include one clear CTA for a 15-minute call.",
    usageCount: 187,
    averageRating: 4.7,
    createdBy: "mem_002",
    createdAt: "2026-03-01T10:00:00Z",
    tags: ["email", "outreach", "personalization"],
  },
  {
    id: "pt_002",
    title: "Blog Post Outline",
    description: "SEO-optimized blog outline with target keywords and section structure",
    category: "marketing",
    promptText: "Create a blog post outline about [TOPIC]. Target keyword: [KEYWORD]. Include: H1 title, 5-7 H2 sections, meta description, and 3 related internal linking opportunities.",
    usageCount: 234,
    averageRating: 4.5,
    createdBy: "mem_001",
    createdAt: "2026-03-05T14:00:00Z",
    tags: ["content", "seo", "writing"],
  },
  {
    id: "pt_003",
    title: "Customer Support Response",
    description: "Empathetic support responses that resolve issues and reduce churn",
    category: "support",
    promptText: "You are a helpful support agent. The customer says: [CUSTOMER_MESSAGE]. Write a response that: 1) acknowledges their frustration, 2) provides a clear solution, 3) offers a next step. Keep it under 200 words.",
    usageCount: 312,
    averageRating: 4.8,
    createdBy: "mem_004",
    createdAt: "2026-03-10T08:00:00Z",
    tags: ["support", "templates", "canned-responses"],
  },
  {
    id: "pt_004",
    title: "Code Review Checklist",
    description: "Generate a structured code review covering bugs, style, performance, and security",
    category: "engineering",
    promptText: "Review this code for: 1) potential bugs, 2) style/readability issues, 3) performance optimizations, 4) security concerns. Code to review:\n```\n[CODE]\n```",
    usageCount: 156,
    averageRating: 4.3,
    createdBy: "mem_003",
    createdAt: "2026-03-15T11:00:00Z",
    tags: ["code", "review", "quality"],
  },
  {
    id: "pt_005",
    title: "Meeting Notes Summarizer",
    description: "Turn raw meeting transcripts into clean, action-oriented summaries",
    category: "productivity",
    promptText: "Summarize these meeting notes:\n\n[TRANSCRIPT]\n\nFormat: 1) Key decisions, 2) Action items with owners, 3) Open questions, 4) Next meeting date if mentioned.",
    usageCount: 278,
    averageRating: 4.6,
    createdBy: "mem_005",
    createdAt: "2026-03-20T09:00:00Z",
    tags: ["meetings", "notes", "productivity"],
  },
  {
    id: "pt_006",
    title: "Job Description Writer",
    description: "Generate inclusive, compelling job descriptions for any role",
    category: "hr",
    promptText: "Write a job description for [ROLE] at [COMPANY]. Include: about us, role overview, key responsibilities (5-7), required qualifications, nice-to-haves, benefits, and EEO statement.",
    usageCount: 94,
    averageRating: 4.4,
    createdBy: "mem_005",
    createdAt: "2026-04-01T08:00:00Z",
    tags: ["hiring", "templates", "writing"],
  },
  {
    id: "pt_007",
    title: "Sales Call Prep Sheet",
    description: "Research-backed prep sheet before any sales call",
    category: "sales",
    promptText: "Create a call prep sheet for [CONTACT] at [COMPANY]. Include: recent company news, LinkedIn summary, potential pain points, 3 discovery questions, and 2 value props tailored to their industry.",
    usageCount: 143,
    averageRating: 4.2,
    createdBy: "mem_002",
    createdAt: "2026-04-10T10:00:00Z",
    tags: ["sales", "research", "preparation"],
  },
  {
    id: "pt_008",
    title: "Data Insights Reporter",
    description: "Turn raw data tables into executive-ready narrative insights",
    category: "data_analysis",
    promptText: "Analyze this data:\n\n[DATA]\n\nProvide: 1) Top 3 insights, 2) Trends over time, 3) Anomalies or outliers, 4) One recommended action. Write for an executive audience.",
    usageCount: 112,
    averageRating: 4.1,
    createdBy: "mem_001",
    createdAt: "2026-04-20T13:00:00Z",
    tags: ["analytics", "reporting", "executive"],
  },
];

export const demoTrainingModules: TrainingModule[] = [
  {
    id: "tm_001",
    title: "ChatGPT Fundamentals",
    description: "Learn prompt basics, context windows, and how to get consistent results from ChatGPT",
    category: "productivity",
    durationMinutes: 45,
    difficulty: "beginner",
    completionRate: 92,
    enrolledCount: 6,
    completedCount: 5,
    lessons: 8,
    practiceScenario: "Rewrite a messy internal status update into a scoped AI request with audience, constraints, and acceptance criteria.",
    capabilityOutcome: "Learner can turn a real workflow need into a reusable prompt without leaking confidential context.",
    reinforcementCadenceDays: 21,
    reinforcementActivity: "Repeat the status-update lab with a new team artifact and peer-review the prompt for confidential context before reuse.",
    criticalThinkingCheckpoint: "Name one assumption in the AI draft, verify its most consequential claim against the source artifact, and record what evidence would make you reject the output.",
    independentJudgmentDrill: "Draft the status-update decision and supporting rationale without AI; only then reveal the model rewrite, compare each changed claim, and keep or revise the original judgment with source evidence.",
    reasoningOwnershipReflection: "After the comparison, rate your confidence in the final status decision, name which reasoning remains yours, and record whether AI saved time without replacing the deeper source review.",
  },
  {
    id: "tm_002",
    title: "Advanced Prompt Engineering",
    description: "Chain-of-thought, few-shot, role-based, and structured output techniques for power users",
    category: "productivity",
    durationMinutes: 90,
    difficulty: "advanced",
    completionRate: 58,
    enrolledCount: 6,
    completedCount: 3,
    lessons: 12,
    practiceScenario: "Build and compare three prompt variants for the same operations report, then explain which output should be trusted.",
    capabilityOutcome: "Learner can evaluate accuracy, assumptions, and decision-readiness instead of only producing more content.",
    reinforcementCadenceDays: 30,
    reinforcementActivity: "Re-run the comparison exercise on a current report, document unsupported claims, and have a reviewer challenge the chosen output.",
    criticalThinkingCheckpoint: "State what could make the selected variant wrong, verify two decision-critical claims against source evidence, and explain why the rejected variants should not be trusted.",
    independentJudgmentDrill: "Score the operations report independently before viewing any AI ranking; then compare the recommendation, revise only where source evidence warrants it, and explain every unchanged decision.",
    reasoningOwnershipReflection: "After choosing a variant, rate confidence in the decision, identify the analysis you still own, and document whether faster generation reduced the depth of evidence review.",
  },
  {
    id: "tm_003",
    title: "Claude for Technical Teams",
    description: "Code generation, debugging, system design reviews, and long-context document analysis with Claude",
    category: "engineering",
    durationMinutes: 75,
    difficulty: "intermediate",
    completionRate: 64,
    enrolledCount: 5,
    completedCount: 3,
    lessons: 10,
    practiceScenario: "Review a simulated architecture brief with Claude and capture risks, source anchors, and follow-up questions for the team.",
    capabilityOutcome: "Learner can use long-context review for engineering judgment while preserving human approval gates.",
    reinforcementCadenceDays: 30,
    reinforcementActivity: "Audit a fresh architecture brief for source-grounded risks and repeat the human-approval handoff with an engineering peer.",
    criticalThinkingCheckpoint: "Separate AI-generated hypotheses from source-backed architecture risks, challenge one plausible but unsupported finding, and document the evidence required for approval.",
    independentJudgmentDrill: "Record an architecture risk assessment before opening Claude; then compare its findings with the human baseline, revise only source-supported judgments, and flag any AI-led change for peer review.",
    reasoningOwnershipReflection: "After the architecture review, state which risk judgments remain yours, rate confidence after challenging Claude, and record any speed-versus-depth trade-off that needs peer review.",
  },
  {
    id: "tm_004",
    title: "AI for Sales & Marketing",
    description: "Prospecting, email sequences, competitive research, content calendars, and social copy with LLMs",
    category: "sales",
    durationMinutes: 60,
    difficulty: "intermediate",
    completionRate: 78,
    enrolledCount: 4,
    completedCount: 3,
    lessons: 9,
    practiceScenario: "Draft a prospecting sequence from approved messaging and mark any claims that require human verification before sending.",
    capabilityOutcome: "Learner can apply AI to role-specific outreach while keeping brand, compliance, and factual-review checks visible.",
    reinforcementCadenceDays: 21,
    reinforcementActivity: "Retake the outreach exercise with a new account and require a peer to verify every external claim before the sequence is approved.",
    criticalThinkingCheckpoint: "Verify each external claim against an approved source, identify one assumption the model made about the prospect, and reject copy whose evidence cannot be traced.",
    independentJudgmentDrill: "Select and substantiate the outreach claims without AI before viewing the generated sequence; then compare differences, reject unsupported changes, and document why each human judgment was kept or revised.",
    reasoningOwnershipReflection: "Before approval, name the outreach claims you personally own, rate confidence after rejecting unsupported copy, and record whether AI speed reduced research or review depth.",
  },
  {
    id: "tm_005",
    title: "Responsible AI & Data Safety",
    description: "Data handling policies, PII protection, bias awareness, and when not to use AI",
    category: "productivity",
    durationMinutes: 40,
    difficulty: "beginner",
    completionRate: 85,
    enrolledCount: 6,
    completedCount: 5,
    lessons: 6,
    practiceScenario: "Classify sample prompts as safe, needs-redaction, or blocked, then document the safer rewrite.",
    capabilityOutcome: "Learner can spot PII, proprietary data, bias risk, and cases where AI should not be used.",
    reinforcementCadenceDays: 14,
    reinforcementActivity: "Review a rotating set of policy-edge prompts, record the safe handling decision, and escalate one ambiguous case for discussion.",
    criticalThinkingCheckpoint: "Explain which evidence supports the handling decision, challenge the model recommendation in one ambiguous case, and escalate rather than accept an unsafe shortcut.",
    independentJudgmentDrill: "Classify each data-handling case without AI before seeing the model recommendation; then compare outcomes, revise only against policy evidence, and escalate any unresolved disagreement.",
    reasoningOwnershipReflection: "After resolving the case, state which safety judgment remains yours, rate confidence after challenging the model, and record whether speed pressure displaced policy review depth.",
  },
];

export const demoUsageLogs: UsageLog[] = [
  { id: "ul_001", memberId: "mem_001", promptTemplateId: "pt_002", channel: "chatgpt", timestamp: "2026-06-09T08:30:00Z", promptSummary: "Blog outline for 'AI adoption trends Q3 2026'", tokensUsed: 1240, manualTimeEstimateMinutes: 75, estimatedTimeSavedMinutes: 42, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_002", memberId: "mem_002", promptTemplateId: "pt_001", channel: "claude", timestamp: "2026-06-09T09:15:00Z", promptSummary: "Cold email to Acme Corp CTO about partnership", tokensUsed: 890, manualTimeEstimateMinutes: 45, estimatedTimeSavedMinutes: 28, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_003", memberId: "mem_004", promptTemplateId: "pt_003", channel: "chatgpt", timestamp: "2026-06-09T10:00:00Z", promptSummary: "Support response for billing dispute #4472", tokensUsed: 560, manualTimeEstimateMinutes: 20, estimatedTimeSavedMinutes: 11, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "neutral" },
  { id: "ul_004", memberId: "mem_003", promptTemplateId: "pt_004", channel: "copilot", timestamp: "2026-06-09T10:45:00Z", promptSummary: "Code review for auth middleware PR #238", tokensUsed: 2100, manualTimeEstimateMinutes: 80, estimatedTimeSavedMinutes: 35, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_005", memberId: "mem_001", promptTemplateId: "pt_008", channel: "chatgpt", timestamp: "2026-06-09T11:30:00Z", promptSummary: "Q2 marketing campaign performance analysis", tokensUsed: 3400, manualTimeEstimateMinutes: 120, estimatedTimeSavedMinutes: 68, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_006", memberId: "mem_005", promptTemplateId: "pt_006", channel: "claude", timestamp: "2026-06-09T12:00:00Z", promptSummary: "JD for Senior Product Designer role", tokensUsed: 780, manualTimeEstimateMinutes: 55, estimatedTimeSavedMinutes: 30, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_007", memberId: "mem_002", promptTemplateId: "pt_007", channel: "chatgpt", timestamp: "2026-06-09T13:15:00Z", promptSummary: "Prep for Enterprise Solutions call at 2pm", tokensUsed: 1650, manualTimeEstimateMinutes: 60, estimatedTimeSavedMinutes: 36, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_008", memberId: "mem_006", promptTemplateId: null, channel: "chatgpt", timestamp: "2026-06-09T07:45:00Z", promptSummary: "Summarize quarterly board report", tokensUsed: 890, manualTimeEstimateMinutes: 40, estimatedTimeSavedMinutes: 18, governanceStatus: "needs_review", governanceReviewReason: "Consumer ChatGPT board-summary use requires data-safety review before ROI credit.", roiEligible: false, feedback: "neutral" },
  { id: "ul_009", memberId: "mem_004", promptTemplateId: "pt_003", channel: "chatgpt", timestamp: "2026-06-08T16:20:00Z", promptSummary: "Respond to feature request from enterprise client", tokensUsed: 620, manualTimeEstimateMinutes: 25, estimatedTimeSavedMinutes: 12, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_010", memberId: "mem_003", promptTemplateId: "pt_004", channel: "copilot", timestamp: "2026-06-08T15:00:00Z", promptSummary: "Review database migration scripts", tokensUsed: 2800, manualTimeEstimateMinutes: 90, estimatedTimeSavedMinutes: 40, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_011", memberId: "mem_001", promptTemplateId: "pt_005", channel: "chatgpt", timestamp: "2026-06-08T13:00:00Z", promptSummary: "Summarize weekly marketing standup", tokensUsed: 450, manualTimeEstimateMinutes: 35, estimatedTimeSavedMinutes: 20, governanceStatus: "approved", governanceReviewReason: null, roiEligible: true, feedback: "positive" },
  { id: "ul_012", memberId: "mem_002", promptTemplateId: null, channel: "chatgpt", timestamp: "2026-06-08T11:30:00Z", promptSummary: "Draft proposal response for RFP questions", tokensUsed: 3200, manualTimeEstimateMinutes: 95, estimatedTimeSavedMinutes: 45, governanceStatus: "needs_review", governanceReviewReason: "Negative RFP draft needs manager review before estimated savings are counted as realized ROI.", roiEligible: false, feedback: "negative" },
];

export const demoCapabilityChecks: CapabilityCheck[] = [
  // Sarah Chen — passed both beginner and advanced modules
  { id: "cc_001", memberId: "mem_001", moduleId: "tm_001", status: "passed", scenario: "Independently rewrote three real team status updates into scoped prompts with audience and constraints, then taught two colleagues the pattern.", attemptedAt: "2026-05-10T14:00:00Z", assessorNotes: "Clear command of scope discipline. No confidential-leak patterns in any output. Pattern transfer to teammates is the strongest signal.", independentApplication: true },
  { id: "cc_002", memberId: "mem_001", moduleId: "tm_002", status: "passed", scenario: "Built and compared three prompt variants for the Q1 marketing attribution report, flagged hallucinated conversion rates in variant B, and selected variant C with supporting evidence for each claim.", attemptedAt: "2026-06-02T11:00:00Z", assessorNotes: "Caught a fabricated metric most trainees miss. Decision documentation is interview-ready for the compliance team.", independentApplication: true },
  { id: "cc_003", memberId: "mem_001", moduleId: "tm_005", status: "passed", scenario: "Classified 20 sample prompts across safe/needs-redaction/blocked, rewrote 5 redaction-risk prompts, and justified each classification to the data safety officer.", attemptedAt: "2026-05-22T09:00:00Z", assessorNotes: "Correctly flagged two borderline cases that the reference key missed. Judgement call rationale was well-documented.", independentApplication: true },

  // Marcus Webb — passed intermediate, has a pending advanced check
  { id: "cc_004", memberId: "mem_002", moduleId: "tm_004", status: "passed", scenario: "Drafted a 5-email prospecting sequence from approved messaging, marked three claims requiring legal review before sending, and adjusted tone per industry after compliance feedback.", attemptedAt: "2026-05-18T15:00:00Z", assessorNotes: "Strong at identifying review gates. Sequence quality improved visibly after one compliance-feedback round.", independentApplication: true },
  { id: "cc_005", memberId: "mem_002", moduleId: "tm_002", status: "pending", scenario: "Evaluate accuracy of three AI-generated competitive research summaries and flag unsupported claims before the team relies on them.", attemptedAt: null, assessorNotes: null, independentApplication: false },

  // Priya Nair — one pass, most modules pending
  { id: "cc_006", memberId: "mem_003", moduleId: "tm_003", status: "passed", scenario: "Reviewed a real PR auth middleware refactor with Claude, documented three risks with source-anchored evidence, and submitted follow-up questions to the architecture team.", attemptedAt: "2026-05-25T10:00:00Z", assessorNotes: "Risk documentation is concrete and source-anchored. Did not lean on the AI to make decisions — used it for evidence gathering.", independentApplication: true },
  { id: "cc_007", memberId: "mem_003", moduleId: "tm_002", status: "pending", scenario: "Build a few-shot prompt chain for triaging support tickets by urgency and category, then validate against 10 real tickets.", attemptedAt: null, assessorNotes: null, independentApplication: false },
  { id: "cc_008", memberId: "mem_003", moduleId: "tm_005", status: "pending", scenario: "Review a colleague's prompt log for PII and proprietary data exposure, document any leaks, and propose safer rewrites.", attemptedAt: null, assessorNotes: null, independentApplication: false },

  // James Okonkwo — pending on most, one needs review
  { id: "cc_009", memberId: "mem_004", moduleId: "tm_001", status: "passed", scenario: "Turned a rambling internal escalation email into a structured AI request with explicit audience, tone, and output format constraints.", attemptedAt: "2026-05-28T08:00:00Z", assessorNotes: "Solid foundational skills. Ready for intermediate modules.", independentApplication: true },
  { id: "cc_010", memberId: "mem_004", moduleId: "tm_004", status: "needs_review", scenario: "Generated a prospecting email that included a claim about the prospect's revenue growth that could not be verified from the provided materials.", attemptedAt: "2026-06-05T16:00:00Z", assessorNotes: "The claim about revenue growth is fabricated — not in any source material provided. Hallucination risk under time pressure. Needs to redo with source-verification step before every claim.", independentApplication: false, reviewOwnerMemberId: "mem_005", reviewDueAt: "2026-06-12T17:00:00Z", remediationPlan: "Redo the sales outreach lab with source-backed claim annotations, then review the final sequence with People Ops before any prospect-facing reuse." },
  { id: "cc_011", memberId: "mem_004", moduleId: "tm_005", status: "pending", scenario: "Audit 15 customer support prompt logs for accidental PII exposure and classify each as safe or needs-redaction.", attemptedAt: null, assessorNotes: null, independentApplication: false },

  // Elena Torres — all passed, high adopter
  { id: "cc_012", memberId: "mem_005", moduleId: "tm_001", status: "passed", scenario: "Taught three HR colleagues how to scope a prompt request using audience, constraints, and acceptance criteria — using only real recruiting workflows as examples.", attemptedAt: "2026-04-15T10:00:00Z", assessorNotes: "Teaching transfer is the strongest signal here. All three colleagues passed their own checks within two weeks.", independentApplication: true },
  { id: "cc_013", memberId: "mem_005", moduleId: "tm_005", status: "passed", scenario: "Reviewed 25 job descriptions for bias language and PII risks using AI, flagged 4, and rewrote them with documented rationale before publishing.", attemptedAt: "2026-05-08T13:00:00Z", assessorNotes: "Bias flagging was precise with no false positives. Rewrites preserved hiring intent while removing exclusionary language.", independentApplication: true },

  // David Park — executive, struggling to transfer training to independent use
  { id: "cc_014", memberId: "mem_006", moduleId: "tm_001", status: "needs_review", scenario: "Asked to rewrite a quarterly board summary using AI but pasted in the full confidential board deck with proprietary financials, revenue projections, and employee headcount data before any redaction.", attemptedAt: "2026-06-01T08:30:00Z", assessorNotes: "Pasted confidential board materials into a consumer AI tool. No data safety checks applied despite completing the Responsible AI module. Needs one-on-one coaching on data handling before any further capability checks.", independentApplication: false, reviewOwnerMemberId: "mem_005", reviewDueAt: "2026-06-08T17:00:00Z", remediationPlan: "Schedule executive data-safety coaching, require a redacted-board-summary retake, and block additional AI usage sign-off until the safety review is passed." },
  { id: "cc_015", memberId: "mem_006", moduleId: "tm_005", status: "pending", scenario: "After coaching, classify 10 executive-typical prompts as safe or needs-redaction, with a written rationale for every classification linked to the data safety policy.", attemptedAt: null, assessorNotes: null, independentApplication: false },
];

export const demoPrePostBenchmarks: PrePostTrainingBenchmark[] = [
  {
    id: "bm_001",
    department: "Customer Support",
    metricName: "Average first-response time",
    unit: "minutes",
    baselineValue: 54,
    postTrainingValue: 31,
    direction: "lower_is_better",
    measuredBefore: "2026-04-01T09:00:00Z",
    measuredAfter: "2026-06-15T09:00:00Z",
    ownerMemberId: "mem_004",
    relatedModuleIds: ["tm_001", "tm_005"],
  },
  {
    id: "bm_002",
    department: "Sales",
    metricName: "Rep research prep time",
    unit: "minutes per call",
    baselineValue: 45,
    postTrainingValue: 24,
    direction: "lower_is_better",
    measuredBefore: "2026-04-03T09:00:00Z",
    measuredAfter: "2026-06-17T09:00:00Z",
    ownerMemberId: "mem_002",
    relatedModuleIds: ["tm_004", "tm_002"],
  },
  {
    id: "bm_003",
    department: "Marketing",
    metricName: "Campaign brief quality score",
    unit: "review score",
    baselineValue: 72,
    postTrainingValue: 86,
    direction: "higher_is_better",
    measuredBefore: "2026-04-05T09:00:00Z",
    measuredAfter: "2026-06-18T09:00:00Z",
    ownerMemberId: "mem_001",
    relatedModuleIds: ["tm_002", "tm_005"],
  },
];

export const demoShadowAiSignals: ShadowAiToolSignal[] = [
  {
    id: "sa_001",
    memberId: "mem_006",
    toolName: "Consumer transcription app",
    detectedAt: "2026-07-28T09:15:00Z",
    observedUse: "Uploaded a confidential board-meeting recording to a personal transcription account to get a summary before the executive briefing.",
    dataSensitivity: "high",
    assessmentStatus: "unassessed",
    reviewerMemberId: "mem_005",
    reviewDueAt: "2026-08-06T17:00:00Z",
    approvedAlternativeTool: null,
    haltProcedureBriefed: false,
  },
  {
    id: "sa_002",
    memberId: "mem_004",
    toolName: "Free web PDF summarizer",
    detectedAt: "2026-07-21T14:40:00Z",
    observedUse: "Pasted an enterprise customer ticket thread with account details into a free web summarizer during a support queue spike.",
    dataSensitivity: "moderate",
    assessmentStatus: "approved_alternative_offered",
    reviewerMemberId: "mem_005",
    reviewDueAt: "2026-08-01T17:00:00Z",
    approvedAlternativeTool: "Approved workspace summarizer with the ticket-redaction prompt template",
    haltProcedureBriefed: false,
  },
  {
    id: "sa_003",
    memberId: "mem_002",
    toolName: "Unreviewed AI email browser extension",
    detectedAt: "2026-07-14T10:05:00Z",
    observedUse: "Installed an unreviewed AI email-drafting extension that can read CRM reply threads to autocomplete prospect responses.",
    dataSensitivity: "high",
    assessmentStatus: "approved_alternative_offered",
    reviewerMemberId: "mem_005",
    reviewDueAt: "2026-07-24T17:00:00Z",
    approvedAlternativeTool: "Approved sales-drafting workspace with CRM data isolation",
    haltProcedureBriefed: true,
  },
];

export const demoAdoptionMetrics: AdoptionMetrics = {
  totalTeamMembers: 6,
  activeUsers: 5,
  totalPromptsUsed: 1292,
  averageAdoptionScore: 76,
  overallTrainingCompletion: 67,
  promptsThisWeek: 87,
  promptsThisMonth: 342,
  previousWeekPrompts: 73,
  previousMonthPrompts: 278,
  trendingUp: true,
  topCategory: "productivity",
  totalPromptTemplates: 8,
  averageRating: 4.5,
  totalCapabilityChecksPassed: 8,
  totalCapabilityChecks: 15,
};
